services:
  wallet-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev -- wallet-app
    ports:
      - 3000:3000
    depends_on:
      - nats
      - transactions-service
    environment:
      - NATS_URL=nats://nats:4222
  transactions-service:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev -- transactions-service
    depends_on:
      - transactions-service-db
      - nats
    environment:
      - POSTGRES_HOST=transactions-service-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
      - NATS_URL=nats://nats:4222
  transactions-service-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    ports:
        - "5433:5432"
  nats:
   image: nats:2.2.2-alpine